language: bash
os: linux

arch:
  - amd64
  - arm64

services:
  - docker

env:
  global:
    - DOCKERHUB="thecaptain989/striptracks-mod"

jobs:
  include:
      stage: BuildImage
      if: (NOT (type IN (pull_request)))
      script:
        # Build variables
        - VERSION=$(git describe --tags --always)
        - VCS_REF=$(git rev-parse --short HEAD)
        - BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        - echo "Build variables:"
        - echo "DOCKERHUB=$DOCKERHUB"
        - echo "VERSION=$VERSION"
        - echo "VCS_REF=$VCS_REF"
        - echo "BUILD_DATE=$BUILD_DATE"
        # Enable multi architecture builds
        - docker buildx create --name mybuilder
        - docker buildx use mybuilder
        # Build image
        - docker buildx build --platform linux/amd64,linux/arm64
          --no-cache
          --build-arg VERSION=${VERSION}
          --build-arg VCS_REF=${VCS_REF}
          --build-arg BUILD_DATE=${BUILD_DATE}
          --build-arg DOCKERHUB=${DOCKERHUB}
          --file Dockerfile
          --tag ${DOCKERHUB}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB}:${TRAVIS_COMMIT} ${DOCKERHUB}:latest
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB}:${TRAVIS_COMMIT}
        - docker push ${DOCKERHUB}:latest
