language: bash
os: linux

arch:
  - amd64
  - arm64

services:
  - docker

env:
  global:
    - DOCKERHUB="thecaptain989/striptracks-mod"

jobs:
  include:
    - os: linux
      arch: amd64
      stage: BuildImage
      if: (NOT (type IN (pull_request)))
      script:
        # Build variables
        - VERSION=$(git describe --tags --always)
        - VCS_REF=$(git rev-parse --short HEAD)
        - BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        - echo "Build variables:"
        - echo "DOCKERHUB=$DOCKERHUB"
        - echo "VERSION=$VERSION"
        - echo "VCS_REF=$VCS_REF"
        - echo "BUILD_DATE=$BUILD_DATE"
        # Build image
        - docker build --no-cache
          --build-arg VERSION=${VERSION}
          --build-arg VCS_REF=${VCS_REF}
          --build-arg BUILD_DATE=${BUILD_DATE}
          --build-arg DOCKERHUB=${DOCKERHUB}
          --file Dockerfile
          --tag ${DOCKERHUB}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB}:${TRAVIS_COMMIT} ${DOCKERHUB}:amd64
        - docker push ${DOCKERHUB}:amd64
    - os: linux
      arch: arm64
      stage: BuildImage 
      if: (NOT (type IN (pull_request)))
      script:
        # Build variables
        - VERSION=$(git describe --tags --always)
        - VCS_REF=$(git rev-parse --short HEAD)
        - BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        - echo "Build variables:"
        - echo "DOCKERHUB=$DOCKERHUB"
        - echo "VERSION=$VERSION"
        - echo "VCS_REF=$VCS_REF"
        - echo "BUILD_DATE=$BUILD_DATE"
        # Build image
        - docker build --no-cache
          --build-arg VERSION=${VERSION}
          --build-arg VCS_REF=${VCS_REF}
          --build-arg BUILD_DATE=${BUILD_DATE}
          --build-arg DOCKERHUB=${DOCKERHUB}
          --file Dockerfile.arm64
          --tag ${DOCKERHUB}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB}:${TRAVIS_COMMIT} ${DOCKERHUB}:arm64
        - docker push ${DOCKERHUB}:arm64
    - script:
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker manifest create ${DOCKERHUB}:latest ${DOCKERHUB}:amd64 ${DOCKERHUB}:arm64
        - docker manifest annotate ${DOCKERHUB}:latest ${DOCKERHUB}:amd64 --os linux --arch amd64
        - docker manifest annotate ${DOCKERHUB}:latest ${DOCKERHUB}:arm64 --os linux --arch arm64
        - docker manifest push ${DOCKERHUB}:latest
        - docker manifest push ${DOCKERHUB}:${TRAVIS_COMMIT}
