#!/usr/bin/with-contenv bash
# shellcheck shell=bash

cat <<EOF
----------------
>>> Striptracks Mod by TheCaptain989 <<<
Repos:
  Dev/test: https://github.com/TheCaptain989/radarr-striptracks
  Prod: https://github.com/linuxserver/docker-mods/tree/radarr-striptracks

Version: {{VERSION}}
----------------
EOF

# Determine if packages need to be installed
commands=(/usr/bin/mkvmerge /usr/bin/sqlite3)
packages=(mkvtoolnix sqlite)
for index in "${!commands[@]}"
do
  if [ ! -f "${commands[$index]}" ]; then
    echo "**** Adding striptracks dependency ${packages[$index]} to package install list ****"
    echo "${packages[$index]}" >> /mod-repo-packages-to-install.list
  else
    echo "**** striptracks dependency ${packages[$index]} already installed, skipping ****"
  fi
done

# Check ownership and attributes on each script file
for file in /usr/local/bin/striptracks*.sh
do
  # Change ownership
  if [ "$(stat -c '%G' "$file")" != "abc" ]; then
    echo "Changing ownership on $file script."
    lsiown abc:abc "$file"
  fi

  # Make executable
  if [ ! -x "$file" ]; then
    echo "Making $file script executable."
    chmod +x "$file"
  fi
done
