#!/usr/bin/with-contenv bash

# Determine if setup is needed
if [ ! -f /usr/bin/mkvmerge ] && \
[ -f /usr/bin/apt ]; then
  # Ubuntu
  echo "Installing MKVToolNix using apt-get"
  apt-get update
  apt-get -y install mkvtoolnix
  rm -rf /var/lib/apt/lists/*
fi
if [ ! -f /usr/bin/mkvmerge ] && \
[ -f /sbin/apk ]; then
  # Alpine
  echo "Installing MKVToolNix using apk"
  apk add mkvtoolnix
  rm -rf /var/lib/apt/lists/*
fi

chmod +x /usr/local/bin/striptracks*.sh
