#!/usr/bin/with-contenv bash

cat <<EOF
>>> Striptracks Mod by TheCaptain989 <<<
Repo: https://github.com/TheCaptain989/radarr-striptracks

Version: $(cat /etc/version.tc989)
EOF

# Determine if setup is needed
if [ ! -f /usr/bin/mkvmerge ]; then
  echo "Running first time setup."

  if [ -f /usr/bin/apt ]; then
    # Ubuntu
    echo "Installing MKVToolNix using apt-get"
    apt-get update && \
    apt-get -y install mkvtoolnix && \
    rm -rf /var/lib/apt/lists/*
  elif [ -f /sbin/apk ]; then
    # Alpine
    echo "Installing MKVToolNix using apk"
    apk add mkvtoolnix && \
    rm -rf /var/lib/apt/lists/*
  else
    # Unknown
    echo "Unknown package manager.  Attempting to install MKVToolNix using apt-get"
    apt-get update && \
    apt-get -y install mkvtoolnix && \
    rm -rf /var/lib/apt/lists/*
  fi

  # Change ownership
  echo "Changing ownership on scripts."
  chown root:users /usr/local/bin/striptracks*.sh

  # Make executable
  echo "Making scripts executable."
  if [ ! -x /usr/local/bin/striptracks.sh ]; then
    chmod +x /usr/local/bin/striptracks*.sh
  fi
fi

