#!/usr/bin/with-contenv bash

# Determine if setup is needed
if [ ! -f /usr/bin/mkvmerge ] && \
[ -f /usr/bin/apt ]; then
  # Ubuntu
  apt-get update
  apt-get -y install mkvtoolnix
  rm -rf /var/lib/apt/lists/*
fi
if [ ! -f /usr/bin/mkvmerge ] && \
[ -f /sbin/apk ]; then
  # Alpine
  apk add mkvtoolnix
  rm -rf /var/lib/apt/lists/*
fi

echo "$VERSION" > /etc/version.tc989
chmod +x /usr/local/bin/striptracks*.sh
